project:
  type: book

book:
  title: "Deep Learning for Predicting Brain Tumor From MRI Images"
  author: "Juan Carlos && Geun Han"
  date: "04/04/2023"
  chapters:
    - abstract.qmd
    - index.qmd
    - intro.qmd
    - eda.qmd
    - methodology.qmd
    - results.qmd
    - conclusion.qmd

format:
  # html:
  #   theme: cosmo
  pdf:
    documentclass: scrreport
    lof: true
    lot: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    format: PrettyPDF-pdf
  # epub:
  #   cover-image: cover.png
