# Pre-Processing and Exploratory Data Analysis
Since we are using images as the datasets, we do not need to consider dropping images and only things that we need to do is to make sure that we are pre-processing the data into the format that the models will take in.

## Data Pre-processing

Some issues to consider to be included:
- Are there missing values in your data? Is there any pattern in whether or not a particular value is missing? How will the missing values be dealt with?
We are inputting images as data for training and testing the models which means that there will not be missing values. However, there might be some limitations since we can pass in argument to the models to take in only a certain number of data. The only pre-processing of the data we are doing is to resize the image into the same size so that models will get the images in the same width and height. This is done by using library called tensorflow. 

Transforming the data will increase the accuracy of the model because all the input data will have the same size which make the models to classify the brain tumors in the images easier.

## Exploratory Data Analysis and Visualisations 

Data visualization is done by matplotlib and seaborn. We are plotting the accuracy, confusion matrix and ROC curve to validate the models. We are also using "evalueate()" function to return the accuracy score of the models for another ascpect of validation. 


